### ISSUE TITLE
App Completions Milestones

### ISSUE THREAD

**Issue by fahshed** [fahshed/kemon-achen-app#32]
**Fahim:**
- [ ] Test flow complete
- [ ] Flatlist Pure component 
- [ ] Pagination Feed
- [ ] Signup

**Akil:**
- [ ] Community Tab scrolling fixed
- [ ] Suggested Professional Backend integration
- [ ] Removing Flatlists in userprofile
- [ ] Removing Not taken tests from user profile
- [ ] Community details about tab unique key for children

**Rishov:**
- [ ] Push Notification
- [ ] Test notification Backend integration

**Akil, Rishov:**
- [ ] Fix the show test history API end points

**Akil, Fahim, RIshov:**
- [ ] Common notification system
- [ ] Text Searching with keywords
- [ ] Segmenting Posts into types such as Q/A, Suggestions, Resources, Assistance
- [ ] Admin 

    - Sign Up Validation
    - Create Test
    - Edit Community About page
