### ISSUE TITLE
App Completions Milestones

### ISSUE THREAD

**Issue by fahshed** [fahshed/kemon-achen-app#33]
**Fahim:**
- [x] Pagination Feed
- [x] Signup
- [x] Test flow complete
- [x] DP
- [x] App Logo 
- [x] Signup flow
- [x] Community, user post redux
- [x] Score bar labels (normal, your)
- [x] Professional notifications

**Akil:**
- [x] Community Tab scrolling fixed
- [x] Suggested Professional Backend integration
- [x] Removing Flatlists in user profile
- [x] Removing Not taken tests from user profile
- [x] Community details about tab unique key for children
- [x] Fix Edit button with conditional rendering for the users
- [x] Text Searching with keywords
- [x] Segmenting Posts into types such as Q/A, Suggestions
- [x] Regular, Professional Conditional ui changes

**Rishov:**
- [x] Push Notification
- [x] Test notification Backend integration
- [x] Advice flow
- [x] Post tag
- [x] Pseudonym
- [x] ActivityIndicator
- [x] Community Tab pull down to refresh

**Akil, Rishov:**
- [x] Fix the show test history API endpoints

**Akil, Fahim, RIshov:**
- [x] Common notification system (Only for show, not clickable)
- [x] Conditional Rendering of User Test History (Low Priority)
- [x] Community Join Button toggling and backend integration
- [x] What will the professional see when he logs in multiples sections:
   - Suggested Professional Screen

**Low Priority Tasks:**
- [ ] Flatlist Pure component 
- [ ] Image Storage and retrieval (Lower Priority)
- [ ] Edit User and Professional Profile (Low Priority)
